### PR TITLE
Upgrade build.jl to Bindeps2 aka BinaryBuilder+BinaryProvider

### PR DESCRIPTION
**Pull request by Gnimuc**
This PR just downloads precompiled FreeType binaries from [here](https://github.com/Gnimuc/FreeTypeBuilder) instead of using package managers and hence addresses @tkelman's concerns in  https://github.com/JuliaGraphics/FreeType.jl/pull/18#issuecomment-279242214. Since this package has no meaningful test, to make sure I didn't do something evil, could you guys help me test this PR in your real applications? 

@SimonDanisch @wgreenr @samuelpowell

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Awesome! I'll try it out today.

**Comment by SimonDanisch** [comment]
Sweet:
```Julia
julia> Pkg.build("FreeType")
INFO: Building FreeType
Info: Downloading https://github.com/Gnimuc/FreeTypeBuilder/releases/download/v2.9/FreeType2.x86_64-w64-mingw32.tar.gz to C:\Users\sdani\.julia\v0.6\FreeType\deps\usr\downloads\FreeType2.x86_64-w64-mingw32.tar.gz...

julia> Pkg.test("FreeType")
INFO: Testing FreeType
INFO: FreeType tests passed
```
I needed to do a Pkg.update though, otherwise there seems to be an API missmatch with BinaryProvider. So you need to require the correct version of BinaryProvider!

**Comment by Gnimuc** [comment]
@SimonDanisch Thanks for the feedback, version bumped. Since this package is not well tested, "INFO: FreeType tests passed" only means the package can be loaded correctly. When I was configuring FreeType in BinaryBuilder, I was aware of some libraries' configuration were missing:
```
Library configuration:
  external zlib: no
  bzip2:         no
  libpng:        no
  harfbuzz:      no
``` 
I hope this wouldn't be harmful to other packages that depends on this one. 

BTW, It seems this package is not in active development: the original author is not watching this repo and some PRs(#22&#21) are still not merged. Currently, some FreeType APIs are still missing, maybe we should follow VulkanCore.jl's way to generate the wrapper using Clang.jl?

**Comment by SimonDanisch** [comment]
>BTW, It seems this package is not in active development: the original author is not watching this repo 

Well, that's why we transferred it to this org ;)

>Currently, some FreeType APIs are still missing, maybe we should follow VulkanCore.jl's way to generate the wrapper using Clang.jl?

That'd be awesome of course, but someone would need to be motivated to invest that time...

**Comment by SimonDanisch** [comment]
>only means the package can be loaded correctly 

Ah yeah I forgot about those minimal tests. I was running Makie with some text which also works fine, though!

**Comment by Gnimuc** [comment]
> That'd be awesome of course, but someone would need to be motivated to invest that time...

OK, I'll look into this(finally got a motivation to learn how to use Clang.jl) :)

**Comment by SimonDanisch** [comment]
Not sure why I ignored this awesome PR for some time now ;) Rebuilding to make sure nothing funky happens with new packages / etc... Then let's merge this :)

**Pull request merged**
