### PR TITLE
Wrapping more headers

### PR DESCRIPTION
**Pull request by Gnimuc**
The generator script is mainly tweaked from VulkanCore.jl. I still need to manually tweak the generated code.

### CODE REVIEW

**Comment by Gnimuc** [comment]
Now, FreeTypeAbstraction.jl's tests have passed with 82fa00a. I hope it should work exactly the same with the latest master. I'll export more APIs and add more tests later on, but maybe not in this PR. Please give it a review at your convenience @SimonDanisch, thanks!

BTW, I find the original wrapper was also firstly generated via Clang.jl and then manually tweaked. I'm basically following the same way except wrapping more headers:sweat_smile:.

**Comment by SimonDanisch** [comment]
Haha, that basically just happened to me with your PR - in the middle of trying to figure out why BinaryBuilder.gcc complains about a missing `<windows.h>`, I remembered your PR :P

**Comment by Gnimuc** [comment]
I'm afraid that I can't make some time for adding tests in the near future, is it a good idea to add FreeTypeAbstraction.jl as a test dependency of this package and simply run `Pkg.test("FreeTypeAbstraction")` in the runtests.jl? 

At a first glance, it's a little bit strange to test the parent package via a descendant.🤔

**Comment by SimonDanisch** [comment]
That sounds fine to me! Some people would recommend avoiding this by including FreeType into FreeTypeAbstraction, but I like it this way ;)

**Comment by Gnimuc** [comment]
rebased

**Comment by SimonDanisch** [comment]
Thank you :)

**Pull request merged**
