### PR TITLE
use the name of the library instead of the full path to work around julia bug

### PR DESCRIPTION
**Pull request by KristofferC**
This works around a bug in Julia on Windows that occurs when trying to make a sysimage that contains FreeType (https://github.com/JuliaLang/julia/issues/34680). This manifested itself when trying to put Makie in a sysimage https://github.com/JuliaComputing/PackageCompilerX.jl/pull/91#issuecomment-582503103.

I understand if a workaround like this is not desired to be merged, but I put it up anyway just for documentation and so that people can try it out to put Makie in the sysimage.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Looks like a pretty harmless change, no?

**Comment by KristofferC** [comment]
I think the `basename` call is not completely correct.

**Comment by KristofferC** [comment]
https://github.com/JuliaGraphics/FreeType.jl/pull/36 seems better

**Comment by SimonDanisch** [comment]
Oh, it certainly does seem better :D

**Pull request closed without merging**
