### PR TITLE
RFC: Regenerate bindings using the latest Clang.jl

### PR DESCRIPTION
**Pull request by Gnimuc**
I spot several bugs when generating these bindings. Clang.jl currently is still not smart when dealing with macros, I'm planning to fix Clang.jl firstly and then revisit this.

### CODE REVIEW

**Comment by Gnimuc** [comment]
hi @SimonDanisch, I'm going to merge this if it won't break Makie.

**Comment by asinghvi17** [comment]
Simon's on vacation unfortunately :)...I'll run some tests locally on Makie though

**Comment by asinghvi17** [comment]
Looks like Makie doesn't break on `FreeType#regenerate`.  `]test Makie` in that environment seems to run without error on latest released.  However, perhaps @mkborregaard could take a final look?

**Comment by mkborregaard** [comment]
That sounds good enough for me, but this is outside my competence.

**Pull request merged**
