### PR TITLE
added FT_Outline_Decompose

### PR DESCRIPTION
**Pull request by wookay**
- added FT_Outline_Decompose
- drop support Julia 0.4

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Sorry for ignoring this! Do you still want this to be merged?

**Comment by wookay** [comment]
it's seems too outdated so it needs for rebase.  I think that it would be better by open another PR.
close this PR.
thanks!

**Comment by wookay** [comment]
It's been already generated using Clang.jl
https://github.com/JuliaGraphics/FreeType.jl/blob/v2.1.2/gen/api/ft_api.jl#L293

**Comment by SimonDanisch** [comment]
Haha nice :) Maybe add your tests then ;)

**Comment by wookay** [comment]
ok. I'm going to investigate the test :)

**Pull request closed without merging**
