### PR TITLE
add appveyor

### PR DESCRIPTION
**Pull request by SimonDanisch**
lets try this to find bugs like from #12 earlier...

### CODE REVIEW

**Comment by SimonDanisch** [comment]
I think you need to activate it on https://ci.appveyor.com/projects 
If you haven't done this before, just sign in with github and click add project!

**Comment by jhasse** [comment]
I think it's better when you activate it on appveyor now that FreeType.jl has been moved to JuliaGraphics ;)

**Comment by SimonDanisch** [comment]
Great, thanks a lot!

**Comment by jhasse** [comment]
No problem! Thank you for continuing working on this :)

**Pull request merged**
