### PR TITLE
added abstraction layer

### PR DESCRIPTION
**Pull request by SimonDanisch**
Added an abstraction layer. Inspired by @aaalexandrov FreeType abstraction (well, some functions are blatantly copied)... Hope this is okay for everyone!

Best,
Simon

### CODE REVIEW

**Comment by SimonDanisch** [comment]
I totally forgot about the dependence on GeometryTypes...
Guess no one would happy to let FreeType depend on it, but it needs to end up in the REQUIRE file in some way.

**Comment by jhasse** [comment]
I wouldn't mind FreeType depending on GeometryTypes. Can you add it to the REQUIRE file and push that commit to your branch?

Where can I find @aaalexandrov FreeType abstraction?

**Comment by SimonDanisch** [comment]
Great!
https://github.com/aaalexandrov/Alex/blob/master/julia/FTFont.jl

**Comment by SimonDanisch** [comment]
Okay, changing it to depend on Julia 0.4 is probably even worse than depending on GeometryTypes.
Well, I can still leave it in [FreeTypeAbstraction](https://github.com/SimonDanisch/FreeTypeAbstraction.jl), if that makes more sense

**Comment by jhasse** [comment]
Yes, at least until 0.4 ist released.

**Pull request closed without merging**
